Dockerfile.aarch64, Dockerfile.x86_64, LICENSE, README.md
This container is used for running the rust-vmm CI. It only works on Linux.
It is currently hosted on Docker Hub under fandree/rust-vmm-dev.
The container image is build using docker manifest so that the latest
tag points to Dockerfile.x86_64 or Dockerfile.arm depending on the
platform.
=> added x86_64 & arm Dockerfiles

Dockerfile.aarch64, Dockerfile.x86_64
We were previously installing the latest available Rust version
with each container build. In order to have reproducible builds,
the Rust version needs to be fixed and manually updated. This will
ensure that we don't have builds on master fail for the various
crates that already use this container that are due to a change
in the compiler.
Fixes: https://github.com/rust-vmm/rust-vmm-container/issues/5
=> Install fixed version of rust

README.md
Previously the container images were pulled from my personal Docker
account. I moved them to the rustvmm organization and instead of
using the latest tag I used version tags.
Since the version tags are now documented, we can consider
https://github.com/rust-vmm/rust-vmm-container/issues/6 fixed.
=> update README to point to rustvmm/dev container

Dockerfile.aarch64, Dockerfile.x86_64, README.md
Update rust version from 1.33 to 1.34. In Rust 1.34 clippy is
available on aarch64 as well.
Fixes: https://github.com/rust-vmm/rust-vmm-container/issues/9
=> Prepare for rustvmm/dev:v2

README.md
The docker hub organization account for rust-vmm project hub is rustvmm
instead of rust-vmm, so correct errors in docker image URLs.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
=> Fix docker image urls

Dockerfile, README.md
And improve the README as well.
=> Dockerfile: Bump the rust toolchain to 1.39

Dockerfile
aarch64 (glibc and musl) is a tier-2 Rust architecture, and not all
components are always available for it. In particular, rustfmt and
clippy seems to be missing for 1.37, 1.38 and 1.39.
This change installs clippy and rustfmt only on the x86_64 toolchains.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> Dockerfile: Only install clippy and rustfmt for x86_64

Dockerfile.windows.x86_64
This image is used for the Windows CI pipeline and is currently
hosted on Docker Hub at lpetrut/rust_win_buildtools (will probably
be moved to a common repo soon).
TODO: document the image annotations that we may want to use when
going with a single Docker repo.
=> Add Windows x86_64 dockerfile

Dockerfile
* The benchmarks integration test in `rust-vmm-ci` will use [`critcmp`](https://github.com/BurntSushi/critcmp) and `git` to get performance numbers before and after a PR.
* Rust is updated to 1.44.1.
* `cargo audit` and `cargo license` will be of use in future integration tests that check for license breaches and vulnerabilities in crates' dependencies.
#27
=> Update Rust, install auditing plugins and necessary tools for running performance tests

Dockerfile
Both tools are useful when building kernels, necessary to test linux-loader/reference VMM facilities.
=> add cpio and bc to the container image

Dockerfile
When the latest cargo-audit was 0.12.0, compilation with Rust 1.44.1 failed; the latest-latest (0.12.1) doesn't have this problem.
=> Remove version restriction on cargo-audit

Dockerfile
This is needed for running `cargo fmt` on code examples.
=> install rust nightly

Dockerfile.windows.x86_64
The Windows docker file is using Rust 1.39. We're going to bump
the version to 1.49, which is used by the Linux container.
=> Bump Windows rust version

Dockerfile, Dockerfile.windows.x86_64, README.md, docker.sh
Resolves #44
```
This commit add a script for easing the build
and publish of new docker containers.
To allow auditability, a json with commit and branch
was added to in the container.
The script will also add a tag from latest built version
to latest alias.
```
Example of run:
```
./docker.sh build
Bulding version new_version
docker build -t rustvmm/dev:12_x86_64 --build-arg RUST_TOOLCHAIN=1.49 --build-arg GIT_BRANCH=issue-44 --build-arg GIT_COMMIT=208f69e8b8d45f21ba09c2777f4e936c8dbc236c -f Dockerfile .
Build completed for rustvmm/dev:12_x86_64
```
```
./docker.sh publish
Publishing 12 and 'latest' on dockerhub
+ echo docker push rustvmm/dev:12_x86_64
docker push rustvmm/dev:12_x86_64
+ echo docker push rustvmm/dev:latest
docker push rustvmm/dev:latest
+ set +e +x
```
To allow …
=> Adds a docker.sh build script

Dockerfile
This upgrade is now long due. This version of Ubuntu also installs a
newer glibc version. In the installation, tzdata needs to be manually
installed because otherwise the build is stalk at selecting the
timezone.
Fixes: https://github.com/rust-vmm/rust-vmm-container/issues/53
=> upgrade to ubuntu 20.04

Dockerfile
Add tools required by bindgen, like clang and musl-tools.
Fixes: #55
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>
=> Add tools required by bindgen

Dockerfile, README.md, docker.sh
- Dockerfile has been simplified by grouping all apt dependencies
in one RUN statement.
- Using --no-install-recommends requires even more explicit list
of dependencies which is good for maintanence.
- No need for Rust nightly because fmt in doc comments is suported
on stable.
- No need to install rustfmt and clippy separately.
Signed-off-by: Sergii Glushchenko <gsserge@amazon.com>
=> Update to Rust 1.58.1 and simplify Dockerfile

Dockerfile
Signed-off-by: Ramyak mehra <rmehra_be19@thapar.edu>
We needed iproute2 to configure tap devices on the host side for testing  virtio-net.
requirements:
test.
=> Added iproute2 as a package for virtio-net testing

README.md
The docker-pull command fails for missing 'v' in $VERSION.
Also, the launched container was not using the latest image as
the hard-coded version value is used in using the container
section. Update documentation in README.md with the fixed commands.
Signed-off-by: nikson <nikson@users.noreply.github.com>
Please see the commit message
requirements:
test.
=> Fix commands in README

Dockerfile
These package are required to be pre-installed for the vhost-device [1]
workspace's gpio crate. This pull reuqest adds support to install them.
This is required to migrate vhost-device to the mainline version of libgpiod [2].
[1] https://github.com/rust-vmm/vhost-device
[2] https://github.com/rust-vmm/vhost-device/pull/279
Signed-off-by: Viresh Kumar <viresh.kumar@linaro.org>
=> Allow libgpiod to be installed and bindgen to be run

Dockerfile
The stable version of libgpiod was released, lets move over to that.
=> Dockerfile: Update libgpio's version

.github/workflows/docker-publish.yml, docker.sh
The step actually needs the full name of the docker registry
+ the tag. Since we are computing this ourselves, we shouldn't need the metadata, so that step is now deleted.
Updated the docker.sh script to just give us the full name.
requirements:
test.
=> fix build-and-push step in workflow

Dockerfile, build_container.sh
Some packages need to build FFI bindings dynamically using 'bindgen' and 'bindgen' requires libclang-dev to be available.
This was removed accidentally by commit d1a36b4b2af5 ("reduce the size occupied during build by container").
Get it back.
=> build_container: Add tools required by bindgen

build_container.sh
libgit2 can consume a lot of memory when cross-compiling for arm64. As suggested here [1], let's use the git executable to prevent this issue.
[1] https://github.com/rust-lang/cargo/issues/10583#issuecomment-1129997984
Fixes: https://github.com/rust-vmm/rust-vmm-container/issues/79
=> build_container: use git cli to avoid OOM on arm64

build_container.sh
cargo-kcov is no longer working as of rust toolchain version 1.71.0, as it can no longer discover test executables. This is due to cargo changing its verbose stdout printing to include the qualified path to rustc, which causes cargo-kcov's string matching to fail.
See also https://github.com/kennytm/cargo-kcov/issues/54
cargo-kcov has had its last commit in 2019, so replace it with cargo-llvm-cov, which is actively maintained, and written for rust.
*Please summarize here why the changes in this PR are needed.*
requirements:
test.
=> Replace cargo-kcov with llvm-cov

build_container.sh
Downloading and installing rustdoc every time the image is built takes considerable time that is not necessary, so specify only the rustup components we need.
requirements:
test.
=> Don't install rustdoc along with default Rust toolchain

build_container.sh
vhost-device-sound has an ALSA audio backend that dynamically links to library libasound2 and also needs its development headers. The pipewire backend also needs a libpipewire version more recent than the packaged ubuntu one, so build it and install it manually.
requirements:
test.
=> Add vhost-device-sound dependencies

.github/workflows/docker-publish.yml
We have a few hoops to jump to get the github action working. I have tested the cosign install works with a temp branch but the PR tests will fail until the workflow has had a chance to install cosign after its merged.
=> github: use current default cosign

build_container.sh
This is useful for verifying that `no_std` crates actually work on `no_std` targets.
See https://github.com/rust-vmm/vm-fdt/pull/68.
requirements:
test.
=> feat(build_container): add no_std-only targets

Dockerfile, docker.sh
This PR fixes an issue introduced in #98 with regards to the `ARCH` env variable not being passed to the build script.
Also updates rust toolchain to 1.75
requirements:
test.
=> Fixing container build script

Dockerfile, build_container.sh, docker.sh
In the previous commits/PR (#99, #98) the ARCH
env variable was introduced to the Dockerfile
and build_container.sh scripts. It was meant to
help with configuration of linux headers for
musl-tools, but did not work for some reason.
Considering the build_container.sh was already
using `uname -m` calls to get the current arch
this commit also uses it, so there is no need
for ARCH anymore.
Also removed `&&` from the scripts and moved `$(uname -m)` to one global var.
For reviewers: don't approve before the CI is finished and it is clear that this PR fixes the issue.
requirements:
test.
Release" section of CHANGELOG.md (if no …
=> fix: replaced ARCH with `uname -m`

build_container.sh
the vhost-device-gpu crate linked here in the PR
https://github.com/rust-vmm/vhost-device/pull/668
contains rutabaga_gfx that requires epoxy library
requirements:
test.
=> Add libepoxy dependencies for vhost-device-gpu

.github/workflows/docker-publish.yml
The current output of the "Generate next docker tag" step is:
Run echo "VERSION=$(./docker.sh print-next-version)" >> $GITHUB_ENV
Next version to be published is:
The next version is not printed, because `$GITHUB_ENV` is loaded at the next step. So at this point we cannot access variables that we are setting in this step.
Use a temporary NEXT_VERSION variable where we save the next version to print it correctly.
=> github: fix "Generate next docker tag" log output

build_container.sh
The vhost-device-gpu crate linked here
rust-vmm/vhost-device#668
contains rutabaga_gfx and the system library packages for rutabaga_gfx crate which is not available in the used ubuntu image, so install the neccessary packages that are available in ubuntu's repositories while for unavailable packages: build and install it manually.
requirements:
test.
=> Build and install packages required by rutabaga_gfx

build_container.sh
The vhost-device-gpu crate linked here
https://github.com/rust-vmm/vhost-device/pull/668
contains rutabaga_gfx and needs some packages and
virglrenderer greater that 1.0.0 which is not available
in the used ubuntu image, so install the neccessary
packages that are available in ubuntu's repositories and
for unavailable packages build and install it manually.
requirements:
test.
=> Build and install additional packages for rutabaga_gfx

Dockerfile
With toolchain version >= 1.80 some crates had regressions due to stricter file descriptor ownership tracking in the standard library (e.g. tracking the same fd in multiple `File` objects, and thus resulting in multiple `close` calls for the same fd will now cause panics in the `drop` impl). We started getting fix-up PRs (https://github.com/rust-vmm/kvm-ioctls/pull/272), so update the CI to 1.80.1 to make sure we don't regress again after merging fixes.
*Please summarize here why the changes in this PR are needed.*
requirements:
test.
Release" section of CHANGELOG.md (if no such section …
=> Update Rust Toolchain to 1.80.1

.github/workflows/docker-publish.yml
Replace `env.REGISTRY` with `index.docker.io` as documentation [1] suggested, since it is empty.
[1] https://github.com/actions/attest-build-provenance#container-image
requirements:
test.
=> github: Fix artifact attestation

.github/workflows/docker-publish.yml, docker.sh
Strip tag from `IMAGE_NAME` used for attest, which should not contain column and tag. `IMAGE_NAME` is now specified explicitly to `rustvmm/dev`.
requirements:
test.
=> github: Fix attest invalid image name

riscv64/build_finalize.sh
Change `nameserver` from `8.8.8.8` to `10.0.2.3` as QEMU User Networking (SLIRP)[1] documents.
[1] https://wiki.qemu.org/Documentation/Networking
Which addresses the network problem when cargo tries to fetch packages from `index.crates.io`.
Fixes: rust-vmm/kvm-bindings#106
requirements:
test.
=> riscv64: Fix VM network

Dockerfile, Dockerfile.riscv64, build_container.sh, riscv64/start_in_qemu.sh
- The `RUST_TOOLCHAIN` is defined separately in each `Dockerfile`, it's
easy to be left behind when trying to update rust toolchain version. By
moving into `build_containers.sh`, effectively eliminates the
possibility of having different rust toolchain version on different
architectures.
- Previous implementation would produce too much useless hint, which leads
to unnecessarily long log output.
This PR also updates rust toolchain version to 1.80.1 on riscv64.
requirements:
test.
=> chore: Refactor toolchain versioning

build_container.sh, docker.sh
Install podman in order to be able to build and run containers inside
the CI container, and install binutils-aarch64-linux-gnu since the
aarch64-linux-gnu-objcopy binary is required to be able to create
aarch64 kernel ELFs for testing.
Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>
=> Add apt dependencies for xen-sys CI tests

.github/workflows/docker-publish.yml, README.md, build_container.sh, docker.sh
- docker.sh: Reuse code as much as possible
- docker.sh: Replace counter tagging with git sha1:
We were using `vXX` counter tagging till `v49` for x86_64 and aarch64,
and `v49-riscv` for riscv64. And we have separated riscv64 from the
other two to another job due to insufficient Github Action time limit
(if the job failed to complete in 6 hours, it will be canceled), which
end up of having two jobs. If the x86_64 and aarch64 job are finished
and images are published in vN, while riscv64 job fails in that run,
restarting the riscv64 job will result an absence of vN and a presence
of v(N+1). So we decided to move on to git sha1 tagging strategy.
Remove `latest` function and `vXX` counter tagging, and use output of
```console
git show -s --format=%h
```
as the tag of images built per PR for …
=> Use `git sha1` instead of counter tagging

Dockerfile, Dockerfile.riscv64, build_container.sh, riscv64/build_finalize.sh
Our downstream communities (cloud-hypervisor, firecracker, kata-containers and etc.) are upgrading to Ubuntu 24.04, propose to catch up.
- base image: Upgrade from Ubuntu 22.04 to 24.04
- ci: Remove work around for aarch64
- build_container: Add p flag while mkdir for dbus
- riscv64: Replace id_rsa.pub with *.pub
requirements:
test.
=> Upgrade ubuntu:22.04 to ubuntu:24.04

build_container.sh
Found in https://github.com/rust-vmm/rust-vmm-container/actions/runs/13650154708/job/38156682477#step:7:2290.
We are having `error: externally-managed-environment` after upgrading to ubuntu:24.04. Remove `EXTERNALLY-MANAGED` file to allow pip to install packages system-wide.
And even if we have `set -e`, if `pip install` fails, the script goes on because we use the && operator.
Avoid this to make sure that we discover any errors with `pip install`.
requirements:
test.
=> build_container: Allow pip to install system-wide

build_container.sh
`rsync` is required for installing kernel headers, which will be used in `seccompiler` crate to generate syscall tables.
requirements:
test.
=> build_container: Install rsync in image

build_container.sh
Time to update to new shiny 2024 edition.
requirements:
test.
=> chore: update Rust to 1.85

.github/workflows/docker-publish.yml, Dockerfile, Dockerfile.riscv64, Dockerfile.windows.x86_64, README.md, build_container.sh, docker.env, docker.ps1, docker.sh
- Added `docker.ps1` to enable building the container using PowerShell with the following command:
```powershell
.\docker.ps1 build
```
And publishing the container using:
```powershell
.\docker.ps1 publish
```
as in `docker.sh` to resolve https://github.com/rust-vmm/rust-vmm-container/issues/49 (Note: didn't update the manifest in `docker.sh`)
- Modified `.github/workflows/docker-publish.yml` to: Add `build-windows` job for Windows containers.
requirements:
test.
=> Add windows docker build script

docker.env
Update Rust version for using some features available in 1.87, like `std::io::pipe`
requirements:
test.
=> chore: update Rust to 1.87

build_container.sh
Some of the rust-vmm crates (such as vmm-sys-util and vm-memory) have
somewhat rudimentary support for MacOS and Windows. While our CI does
not have the means to test these platforms (the rust-vmm CI runners are
linux-only), it can at least do some simple compile testing using `cargo
check` (as long as we do not have any build dependencies that try to
compile native libraries). For this, install the required cargo targets
into the docker container, such that crates that wish to do such compile
testing can specify such additional tests in their custom tests
pipelines.
While we're here, also revert #135, because we ended up not needing the utility.
requirements:
`git commit -s`), and the commit message has max 60 …
=> install rustup targets for MacOS and Windows 

build_container.sh
Some crates have a myriad of features, and it is very easy to
accidentally mess up imports in a way that `cargo check --all-features`
works, but only compiling with only a subset of features breaks. For
this scenario, cargo check-all-features can help, as it will attempt to
compile all feature permutations.
We can even add this to the default CI, even for crates like vhost that
have incompatible features, due to cargo-all-features allowing the
elimination of incompatible features from the test matrix [1].
Some usecases where this could have been helpful is in vm-memory, where
we have tens of feature permutations, and some of them invariably get
broken regularly [2], or in crates that have no-std support that is
offered via an opt-out 'std' feature [3]
[1]: …
=> Add cargo-all-features to docker container
