rust-vmm/rust-vmm-container

Dockerfile, README.md
=> Adds shellcheck tool

Dockerfile, README.md
=> Install python tools

README.md, docker.sh
The v12 container based on these changes is already published on Docker Hub.
=> Use Rust 1.52.1

Dockerfile
This reverts commit cae2b0d889e2a6ac48e4a9b3abe2c4d26596e754.
=> Revert "Add tools required by bindgen"

README.md, docker.sh
Signed-off-by: Sergii Glushchenko <gsserge@amazon.com>
=> Use Rust 1.54

Dockerfile, docker.sh
- Update to 1.63.0
- Install nightly + fuzz
requirements:
test.
=> Update rust  version & install fuzz tools

docker.sh
Update the Rust toolchain to the latest version.
requirements:
test.
=> update rust version to 1.66.1

docker.sh
We're going to publish a new version to add support for libgpio. We can use this opportunity to also update to the latest publish rust version.
requirements:
test.
=> update to Rust 1.67.1

CODEOWNERS
Explicitly add myself & lauralg as a owner. Also, adding Stefano & Alex.
Signed-off-by: Andreea Florescu <fandree@amazon.com>
*Please summarize here why the changes in this PR are needed.*
requirements:
test.
=> add more codeowners

.github/workflows/docker-publish.yml
We were not being explicit about where to publish the container, which was leading to a permission denied problem as it was trying to push it to a default repository name called "library".
requirements:
test.
=> explicit name of the docker container

build_container.sh
It's a requirements for miri that I missed in #82 - sorry 'bout that (this time I checked that all requirements for miri are there though)
requirements:
test.
=> Add rust-src component for nightly toolchain

Dockerfile
Update Rust toolchain to 1.72.0
requirements:
test.
=> chore: Update Rust toolchain to 1.72.0

build_container.sh
This PR reduces pipewire dependencies and install `dbus` (needed to run pipewire).
CC @epilys 
requirements:
test.
=> pipewire followup

build_container.sh
Added musl-tools package. It is needed for some rust crates to compile for musl target.
requirements:
test.
=> feat(build_container): added musl-tools

Dockerfile, build_container.sh
This PR is an addition to the #97 PR and helps musl-tools to find linux headers.
requirements:
test.
=> feat(build_container): help musl-tools find headers

README.md
add documetation on how to build and test your
changes locally with the Container Image. This
would help verify that the changes you are making
works as intended locally before submitting your PR
requirements:
test.
=> README.md: Document testing changes locally

CODEOWNERS
Add @TimePrinciple to maintain `rust-vmm-container` RISC-V part.
requirements:
test.
=> Add TimePrinciple to CODEOWNERS

build_container.sh
Update Rust to the latest release to catch if new versions cause any havoc.
See: https://github.com/rust-vmm/kvm/pull/298
requirements:
test.
=> chore: update Rust to 1.83

build_container.sh
Needed for https://github.com/rust-vmm/community/issues/183, to replace out homegrown, file-based coverage checks with codecov.io.
*Please summarize here why the changes in this PR are needed.*
requirements:
test.
=> Install codecov.io uploader into container

build_container.sh
Add dependencies required for the gstreamer audio backend.
requirements:
test.
=> Add dependencies for gstreamer
